src/Entity/Link.php
<?php

namespace App\Entity;

use App\Repository\LinkRepository;
use App\ValueObject\LinkMeta;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LinkRepository::class)]
class Link
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Embedded(class: LinkMeta::class, columnPrefix: 'meta_')]
    private LinkMeta $meta;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $visit_at = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $click_count = null;

    #[ORM\Column]
    private ?int $unique_visit_count = null;

    #[ORM\Column]
    private ?int $total_visit_count = null;

    #[ORM\Column]
    private ?bool $has_automatic_redirect = null;

    #[ORM\Column(nullable: true)]
    private ?int $redirect_delay = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->meta = LinkMeta::default();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getVisitAt(): ?\DateTimeImmutable
    {
        return $this->visit_at;
    }

    public function setVisitAt(\DateTimeImmutable $visit_at): self
    {
        $this->visit_at = $visit_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getClickCount(): ?int
    {
        return $this->click_count;
    }

    public function setClickCount(int $click_count): self
    {
        $this->click_count = $click_count;

        return $this;
    }

    public function getUniqueVisitCount(): ?int
    {
        return $this->unique_visit_count;
    }

    public function setUniqueVisitCount(int $unique_visit_count): self
    {
        $this->unique_visit_count = $unique_visit_count;

        return $this;
    }

    public function getTotalVisitCount(): ?int
    {
        return $this->total_visit_count;
    }

    public function setTotalVisitCount(int $total_visit_count): self
    {
        $this->total_visit_count = $total_visit_count;

        return $this;
    }

    public function isHasAutomaticRedirect(): ?bool
    {
        return $this->has_automatic_redirect;
    }

    public function setHasAutomaticRedirect(bool $has_automatic_redirect): self
    {
        $this->has_automatic_redirect = $has_automatic_redirect;

        return $this;
    }

    public function getRedirectDelay(): ?int
    {
        return $this->redirect_delay;
    }

    public function setRedirectDelay(?int $redirect_delay): self
    {
        $this->redirect_delay = $redirect_delay;

        return $this;
    }

    public function getMeta(): LinkMeta
    {
        return $this->meta;
    }

    public function setMeta(LinkMeta $meta): self
    {
        $this->meta = $meta;

        return $this;
    }
}

src/Controller/LinkController.php
<?php

namespace App\Controller;

use App\Entity\Link;
use App\Form\CreateLinkType;
use App\Form\UpdateLinkType;
use App\Message\CreateLinkMessage;
use App\Message\DeleteLinkMessage;
use App\Message\UpdateLinkMessage;
use App\Repository\LinkRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/link')]
class LinkController extends AbstractController
{
    public function __construct(
        private readonly MessageBusInterface $bus
    ) {
    }

    #[Route('/', name: 'app_link_index', methods: ['GET'])]
    public function index(LinkRepository $linkRepository): Response
    {
        return $this->render('link/index.html.twig', [
            'links' => $linkRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_link_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LinkRepository $linkRepository): Response
    {
        $message = new CreateLinkMessage();
        $form = $this->createForm(CreateLinkType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->bus->dispatch($message);

            return $this->redirectToRoute('app_link_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('link/new.html.twig', [
            'link' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_link_show', methods: ['GET'])]
    public function show(Link $link): Response
    {
        return $this->render('link/show.html.twig', [
            'link' => $link,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_link_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Link $link, LinkRepository $linkRepository): Response
    {
        $message = new UpdateLinkMessage($link);
        $form = $this->createForm(UpdateLinkType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->bus->dispatch($message);

            return $this->redirectToRoute('app_link_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('link/edit.html.twig', [
            'link' => $link,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_link_delete', methods: ['POST'])]
    public function delete(Request $request, Link $link, LinkRepository $linkRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$link->getId(), $request->request->get('_token'))) {
            $this->bus->dispatch(new DeleteLinkMessage($link));
        }

        return $this->redirectToRoute('app_link_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/link/_delete_form.html.twig
<form method="post" action="{{ path('app_link_delete', {'id': link.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ link.id) }}">
    <button class="btn">Delete</button>
</form>

templates/link/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/link/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Link{% endblock %}

{% block body %}
    <h1>Edit Link</h1>

    {{ include('link/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_link_index') }}">back to list</a>

    {{ include('link/_delete_form.html.twig') }}
{% endblock %}

templates/link/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Link index{% endblock %}

{% block body %}
    <h1>Link index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Url</th>
                <th>Slug</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Visit_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for link in links %}
            <tr>
                <td>{{ link.id }}</td>
                <td>{{ link.url }}</td>
                <td>{{ link.slug }}</td>
                <td>{{ link.createdAt ? link.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ link.updatedAt ? link.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ link.visitAt ? link.visitAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_link_show', {'id': link.id}) }}">show</a>
                    <a href="{{ path('app_link_edit', {'id': link.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_link_new') }}">Create new</a>
{% endblock %}

templates/link/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Link{% endblock %}

{% block body %}
    <h1>Create new Link</h1>

    {{ include('link/_form.html.twig') }}

    <a href="{{ path('app_link_index') }}">back to list</a>
{% endblock %}

templates/link/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Link{% endblock %}

{% block body %}
    <h1>Link</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ link.id }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ link.url }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ link.slug }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ link.createdAt ? link.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ link.updatedAt ? link.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Visit_at</th>
                <td>{{ link.visitAt ? link.visitAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_link_index') }}">back to list</a>

    <a href="{{ path('app_link_edit', {'id': link.id}) }}">edit</a>

    {{ include('link/_delete_form.html.twig') }}
{% endblock %}